### ISSUE TITLE
Re-arrange tabs in dashboards

### ISSUE THREAD

**Issue by rbutleriii** [Longo-Lab/de_dashboards#17]
We should organize the tabs to make better use of the upper & lower space
- [ ] All the "table" type tabs should be moved to the lower half
- [ ] The `Summary table` tab should be first on the lower, so viewers can see the thresholds right away.

**Comment by cyouh95** [comment]
Perhaps alternatively, we could have collapsible tabs for the gProfiler/GSEA results and keep all analyses results on the top half. I do kind of like how the analyses and the genes are separated in the 2 halves, might make it more clear to the users + easier to explain in the documentation the way it's structured now.

For the thresholds, maybe we can move that info to the sidebar instead of in the summary table tab?

Both are currently implemented in `t41b_BD10-2_stim` to see how that looks, but open to any changes!

**Comment by rbutleriii** [comment]
The collapsible part is good, we can keep it that way. I think in terms of the expanded set though, it might be a little harder for someone to click back and forth between the GSEA plots, with the result tables in between. Maybe reorder them so all the plots come first and all the tables second?

Also , try the cite and credit stuff to the header on the upper right since that is unoccupied.

**Comment by rbutleriii** [comment]
Also, I noticed for the GSEA table, there should be a `padj` in addition to the `NES` value for each GO, so we should add that column to the table.

**Comment by cyouh95** [comment]
Added to [T41B_BD10-2_stim](https://longo-stanford.shinyapps.io/de_T41B_BD10-2_stim/):

- All plots before tables for gProfiler and GSEA tabs
- P-adj column added to GSEA tables
- Citation added to header

**Comment by rbutleriii** [comment]
Excellent, good job.
